---
# Organization to pull metrics from
organization: 'neuroinformatics-unit'

# Start date to pull metrics from
since: '2019-01-01'

# GitHub Pages path to the repository
# Used for handling relative paths for assets
basePath: '/org-metrics-dashboard'
